reserved:
  id: 0x00
  type: i32
  default: 0

qcomp_alpha:
  id: 0x01
  type: f32
  default: 0.05

qcomp_beta:
  id: 0x02
  type: f32
  default: 0.97

theta_kp:
  id: 0x03
  type: f32
  default: 0.05

theta_ki:
  id: 0x04
  type: f32
  default: 1e-12

ed_kp:
  id: 0x05
  type: f32
  default: 0.8

ed_ki:
  id: 0x06
  type: f32
  default: 0.0

vdesired_kp:
  id: 0x07
  type: f32
  default: 1.0

vdesired_ki:
  id: 0x08
  type: f32
  default: 0.0

wdesired_kp:
  id: 0x09
  type: f32
  default: 1.0

wdesired_ki:
  id: 0x0a
  type: f32
  default: 0.0

wheel_radius:
  id: 0x0b
  type: f32
  default: 1.0

wheel_distance:
  id: 0x0c
  type: f32
  default: 1.0

blink_period:
  id: 0x0d
  type: f32
  default: 0.0

madgwick_beta:
  id: 0x0e
  type: f32
  default: 5

imu_filter_type:
  id: 0x0f
  type: u32
  default: 3

mahony_kp:
  id: 0x10
  type: f32
  default: 0.37

imu_calibration_samples:
  id: 0x11
  type: u32
  default: 500

imu_publish_period:
  id: 0x12
  type: u32
  default: 10000

motor_pwm_refresh_period:
  id: 0x13
  type: u32
  default: 10000

control_debug_enable:
  id: 0x14
  type: u32
  default: 0

control_debug_publish_period:
  id: 0x15
  type: u32
  default: 33333

imu_raw_enable:
  id: 0x16
  type: u32
  default: 0

motor_output_enable:
  id: 0x17
  type: u32
  default: 1

motor_output_publish_period:
  id: 0x18
  type: u32
  default: 33333

mag_calib_b0:
  id: 0x19
  type: f32
  default: -157.98802123

mag_calib_b1:
  id: 0x1a
  type: f32
  default: 29.90416336

mag_calib_b2:
  id: 0x1b
  type: f32
  default: -170.7587217

mag_calib_m00:
  id: 0x1c
  type: f32
  default: 1.91202375

mag_calib_m01:
  id: 0x1d
  type: f32
  default: 0.00451775

mag_calib_m02:
  id: 0x1e
  type: f32
  default: -0.02390958

mag_calib_m10:
  id: 0x1f
  type: f32
  default: 0.00451775

mag_calib_m11:
  id: 0x20
  type: f32
  default: 1.92767187

mag_calib_m12:
  id: 0x21
  type: f32
  default: -0.03320508

mag_calib_m20:
  id: 0x22
  type: f32
  default: -0.02390958

mag_calib_m21:
  id: 0x23
  type: f32
  default: -0.03320508

mag_calib_m22:
  id: 0x24
  type: f32
  default: 2.06441668

accel_calib_b0:
  id: 0x25
  type: f32
  default: 0.00770027

accel_calib_b1:
  id: 0x26
  type: f32
  default: -0.00205022

accel_calib_b2:
  id: 0x27
  type: f32
  default: -0.10933483

accel_calib_m00:
  id: 0x28
  type: f32
  default: 9.80959641

accel_calib_m01:
  id: 0x29
  type: f32
  default: 0.0

accel_calib_m02:
  id: 0x2a
  type: f32
  default: 0.0

accel_calib_m10:
  id: 0x2b
  type: f32
  default: 0.0

accel_calib_m11:
  id: 0x2c
  type: f32
  default: 9.77402776

accel_calib_m12:
  id: 0x2d
  type: f32
  default: 0.0

accel_calib_m20:
  id: 0x2e
  type: f32
  default: 0.0

accel_calib_m21:
  id: 0x2f
  type: f32
  default: 0.0

accel_calib_m22:
  id: 0x30
  type: f32
  default: 9.72531012

controller_timeout:
  id: 0x31
  type: u32
  default: 1000000

lane_lookahead:
  id: 0x32
  type: f32
  default: -100.0

lane_inlier_threshold:
  id: 0x33
  type: u32
  default: 100

lane_slope_limit:
  id: 0x34
  type: f32
  default: 0.5
