camera:
  model:
    width: 1280
    height: 720
    fx: 522.20712654655472
    fy: 523.19742805358726
    cx: 643.13767986134133
    cy: 354.09258793054227
    k1: 0.067843083931715092
    k2: -0.059556359514984794
    p1: 0
    p2: 0
    k3: 0
  pose:
    position: [0.36, 0.0, -0.33]
    attitude: [0.0, -25.0, 0.0]

estimator:
  pos_filter:
    alpha: 0.2
    beta: 1.0e-3
  att_filter:
    alpha: 0.5
    beta: 2.0
  median: 4

renderer:
  area:
    width: 3
    height: 3
  spot:
    width: 0.15
    length: 0.95
    percent: 0.25
  strip:
    width: 0.02
  chassis:
    length: 0.50
    width: 0.1
    height: 0.1
    offset: 0.13
  wheel:
    radius: 0.0175
    width: 0.02
    offset: 0.05
  marker:
    border: 0.02

sim:
  model:
    R: 0.0175
    L: 0.05
    M: 2.0
    d: 0.3
    J: 0.06167
    B: 2.0
    h: 0.3
    Kb: 0.06820926132509801
    Ki: 0.45
    Rs: 1.25
  north_offset: 30
  dt: 1.0e-3
  cam_dt: 0.1
  initial:
    w: 0.0
    v: 0.0
    yaw: -45.0
    x: 1
    y: 1

markers:
  - id: 20
    size: 0.27
    role: 'goal'
    pose:
      position: [0.75375, 2.4575, -0.02]
      attitude: [0.0, 0.0, 90.0]
  - id: 38
    size: 0.2
    role: 'landmark'
    pose:
      position: [1.50823, 1.50823, 0.02]
      attitude: [0.0, 0.0, 45.0]
  - id: 39
    size: 0.2
    role: 'landmark'
    pose:
      position: [-1.50823, 1.50823, -0.02]
      attitude: [0.0, 0.0, 135.0]
  - id: 53
    size: 0.2
    role: 'landmark'
    pose:
      position: [-1.50823, -1.50823, -0.02]
      attitude: [0.0, 0.0, 225.0]
  - id: 59
    size: 0.2
    role: 'landmark'
    pose:
      position: [1.50823, -1.50823, -0.02]
      attitude: [0.0, 0.0, 315.0]
  - id: 30
    size: 0.2
    role: 'landmark'
    pose:
      position: [1.5075, 0.0, -0.02]
      attitude: [0.0, 0.0, 0.0]
  - id: 44
    size: 0.2
    role: 'landmark'
    pose:
      position: [0.0, 1.5075, -0.02]
      attitude: [0.0, 0.0, 90.0]
  - id: 57
    size: 0.2
    role: 'landmark'
    pose:
      position: [-1.5075, 0.0, -0.02]
      attitude: [0.0, 0.0, 180.0]
  - id: 71
    size: 0.2
    role: 'landmark'
    pose:
      position: [0.0, -1.5075, -0.02]
      attitude: [0.0, 0.0, 270.0]

manual_control:
  forward_backward: 1.0
  left_right: 1.0
  mixed_1: 1.0
  mixed_2: 0.1
