runner:
  - cmd: "longthin-bridge"
    args: ["/dev/ttyAMA0"]
  - cmd: "longthin-estimator"
    args: ["--video", "picam:"]
  - cmd: "longthin-ekf"
    args: []
  - cmd: "longthin-planner"
    args: []