#define LTPARAMS_COUNT 0x16
extern union ltparam_t ltparams[LTPARAMS_COUNT];

enum ltparams_index_t {
	LTPARAMS_RESERVED = 0x00,
	LTPARAMS_QCOMP_ALPHA = 0x01,
	LTPARAMS_QCOMP_BETA = 0x02,
	LTPARAMS_THETA_KP = 0x03,
	LTPARAMS_THETA_KI = 0x04,
	LTPARAMS_ED_KP = 0x05,
	LTPARAMS_ED_KI = 0x06,
	LTPARAMS_VDESIRED_KP = 0x07,
	LTPARAMS_VDESIRED_KI = 0x08,
	LTPARAMS_WDESIRED_KP = 0x09,
	LTPARAMS_WDESIRED_KI = 0x0a,
	LTPARAMS_WHEEL_RADIUS = 0x0b,
	LTPARAMS_WHEEL_DISTANCE = 0x0c,
	LTPARAMS_BLINK_PERIOD = 0x0d
};

static const enum ltparams_type_t ltparams_types[LTPARAMS_COUNT] = {
	[LTPARAMS_RESERVED] = LTPARAMS_TYPE_UINT32,
	[LTPARAMS_QCOMP_ALPHA] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_QCOMP_BETA] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_THETA_KP] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_THETA_KI] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_ED_KP] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_ED_KI] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_VDESIRED_KP] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_VDESIRED_KI] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_WDESIRED_KP] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_WDESIRED_KI] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_WHEEL_RADIUS] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_WHEEL_DISTANCE] = LTPARAMS_TYPE_FLOAT,
	[LTPARAMS_BLINK_PERIOD] = LTPARAMS_TYPE_FLOAT
};