camera:
  model:
    width: 1280
    height: 720
    fx: 545.98798902771057
    fy: 543.6599611096507
    cx: 645.23625834586369
    cy: 360.08728645824363
    k1: 0.062681962274686281
    k2: -0.069663556955777112
    p1: 0
    p2: 0
    k3: 0.004866869450794095
  pose:
    position: [0.4, 0.0, -0.3]
    attitude: [0.0, -30.0, 0.0]

estimator:
  pos_filter:
    alpha: 0.5
    beta: 0.7
  att_filter:
    alpha: 0.5
    beta: 2.0
  median: 8

renderer:
  area:
    width: 3
    height: 3
  spot:
    width: 0.15
    length: 0.75
    percent: 0.3
  strip:
    width: 0.02
  chassis:
    length: 0.5
    width: 0.1
    height: 0.1
    offset: 0.1
  wheel:
    radius: 0.0175
    width: 0.02
    offset: 0.05
  marker:
    border: 0.02

sim:
  model:
    R: 0.0175
    L: 0.05
    M: 2.0
    d: 0.3
    J: 0.06167
    B: 5.0
    h: 0.3
    Kb: 0.06820926132509801
    Ki: 0.45
    Rs: 1.25
  dt: 1.0e-3

markers:
  - id: 38
    size: 0.2
    pose:
      position: [1.50823, 1.50823, 0.02]
      attitude: [0.0, 0.0, 45.0]
  - id: 39
    size: 0.2
    pose:
      position: [-1.50823, 1.50823, -0.02]
      attitude: [0.0, 0.0, 135.0]
  - id: 53
    size: 0.2
    pose:
      position: [-1.50823, -1.50823, -0.02]
      attitude: [0.0, 0.0, 225.0]
  - id: 59
    size: 0.2
    pose:
      position: [1.50823, -1.50823, -0.02]
      attitude: [0.0, 0.0, 315.0]
  - id: 30
    size: 0.2
    pose:
      position: [1.5075, 0.0, -0.02]
      attitude: [0.0, 0.0, 0.0]
  - id: 44
    size: 0.2
    pose:
      position: [0.0, 1.5075, -0.02]
      attitude: [0.0, 0.0, 90.0]
  - id: 57
    size: 0.2
    pose:
      position: [-1.5075, 0.0, -0.02]
      attitude: [0.0, 0.0, 180.0]
  - id: 71
    size: 0.2
    pose:
      position: [0.0, -1.5075, -0.02]
      attitude: [0.0, 0.0, 270.0]
# - id: 20
#    size: 0.27
#    pose:
#      position: [0.81, 2.4575, -0.02]
#      attitude: [0.0, 0.0, 90.0]

manual_control:
  forward_backward: 1.0
  left_right: 1.0
  mixed_1: 1.0
  mixed_2: 0.1